export const FETH_ALL_PLAYS = {
  display: "Simple fetch play",
  name: "Fetch_Plays",
  function: "plays",
  write: false,
  params: [
    "blog",
    "style",
    "component",
    "cover",
    "created_at",
    "description",
    "featured",
    "github",
    "id",
    "dev_mode",
    "language",
    { level: ["name"] },
    "name",
    "path",
    { play_tags: { tag: ["name"] } },
    "updated_at",
    { user: ["id", "displayName", "avatarUrl"] },
    "video",
  ],
};
